par(mfrow=c(2,2))
plot(file$Global_active_power~file$Date_Time,,type="l",xlab="",ylab="Global Active Power")
plot(file$Voltage~file$Date_Time,,type="l",xlab="",ylab="Voltage")
plot(file$Date_Time,type="n",file$Sub_metering_1,xlab="",ylab="Energy sub metering")
points(file$Date_Time,file$Sub_metering_1,type="l",col="black")
points(file$Date_Time,file$Sub_metering_2,type="l",col="red")
points(file$Date_Time,file$Sub_metering_3,type="l",col="blue")
legend("topright",lty=1,lwd=1,bty="n",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(file$Global_reactive_power~file$Date_Time,,type="l",xlab="",ylab="Global_reactive_power")
dev.copy(png,"plot4.png",height=480,width=480)
dev.off()
